wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    code_path: code/baseline.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.12
    start_time: 1736863370.946151
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.10.12
      5: 0.13.11
      8:
      - 5
anneal_lr:
  desc: null
  value: true
batch_size:
  desc: null
  value: 2048
capture_video:
  desc: null
  value: false
clip_coef:
  desc: null
  value: 0.2
clip_vloss:
  desc: null
  value: true
cuda:
  desc: null
  value: false
ent_coef:
  desc: null
  value: 0.0
env_id:
  desc: null
  value: LunarLanderContinuous-v2
eval_interval:
  desc: null
  value: 10
exp_name:
  desc: null
  value: baseline
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
hf_entity:
  desc: null
  value: ''
learning_rate:
  desc: null
  value: 0.0003
max_grad_norm:
  desc: null
  value: 0.5
minibatch_size:
  desc: null
  value: 64
norm_adv:
  desc: null
  value: true
num_envs:
  desc: null
  value: 1
num_iterations:
  desc: null
  value: 488
num_minibatches:
  desc: null
  value: 32
num_steps:
  desc: null
  value: 2048
save_model:
  desc: null
  value: false
seed:
  desc: null
  value: 1
target_kl:
  desc: null
  value: null
torch_deterministic:
  desc: null
  value: true
total_timesteps:
  desc: null
  value: 1000000
track:
  desc: null
  value: true
update_epochs:
  desc: null
  value: 10
upload_model:
  desc: null
  value: false
vf_coef:
  desc: null
  value: 0.5
wandb_entity:
  desc: null
  value: csherstan-team
wandb_project_name:
  desc: null
  value: cleanSR
